{"version":1,"ops":[{"type":1,"author":{"id":"c89f7af509e1fcb8f142d9c75e042be0d701c853"},"timestamp":1583574592,"metadata":{"github-id":"MDU6SXNzdWU1NzczMDk5MTY=","github-url":"https://github.com/perl11/cperl/issues/409","origin":"github"},"title":"Deep recursion error from function that isn't even recursive","message":"I get this failure in the Type-Tiny 1.010000 test suite:\n\n```\nDeep recursion on subroutine \"Test::TypeTiny::should_fail\" at t/20-unit/Types-Common-Numeric/ranges.t line 44.\n```\n\nBut `should_fail` isn't a recursive function. It does do a `goto \\\u0026Test::More::ok` at the end after setting `@_` so this could be a problem with cperl's tail call optimizations?","files":null}]}