{"version":1,"ops":[{"type":1,"author":{"id":"d84ad93fabc8df4b7aa86a0a5908d30931d8168c"},"timestamp":1527690154,"metadata":{"github-id":"MDU6SXNzdWUzMjc3NTQzMzA=","github-url":"https://github.com/perl11/cperl/issues/365","origin":"github"},"title":"Coro: segfault (perl-5.24+)","message":"Testcase:\n```perl\nuse Coro;\n\nsub _sleep {\n    my $c = Coro::rouse_cb();\n    Coro::rouse_wait();\n}\n\nmy $child = async {\n    my ($a, $a2, $a3\n# remove following line to omit segfault\n        , $a4, $a5, $a6, $a7, $a8, $a9\n    );\n\n    _sleep();\n};\n\ncede;\nwarn \"canceling\";\n$child-\u003ecancel();\n```\nSegfault occurs in scope.c: Perl_leave_scope.\nIt seems like this bug also affects p5p. First bad commit is e8a84ef.","files":null}]}